lbweight = input("Introducir 'PESO' en libras\n")
inchlength = input("Introducir la dimension 'LARGO' en pulgadas\n")
inchwidth = input("Introducir la dimension 'ANCHO' en pulgadas\n")
inchheight = input("Introducir la dimension 'ALTO' en pulgadas\n")
kgweight = ((float(lbweight)) * 0.45359237)
mlength = ((float(inchlength) / 39.37))
mwidth = ((float(inchwidth) / 39.37))
mheight = ((float(inchheight) / 39.37))
mdim = (mlength) * (mwidth) * (mheight)
print("Peso en Kg:", kgweight)
print("Dimensiones:", mlength, "x", mwidth, "x", mheight)
print("CBM:", mdim)
